Add IPv6 support to netmask and gateway fields
xcp-ng/xsconsole pull request #3
Opened 2023-11-16 15:33 UTC by Nambrok

2023-11-16 15:34 UTC, Nambrok commented
@benjamreis @stormi  In need of review

2023-11-16 16:31 UTC, benjamreis requested changes
You added back an old logic, you only need to check the right field in XAPI depending on IPv6 or not.

2023-11-16 16:31 UTC, benjamreis commented on XSConsoleData.py
This code is no longer relevant Whatever the mode the netmask should be read from xapi.

2023-11-16 16:31 UTC, benjamreis commented on XSConsoleData.py
Same as above.

2023-11-17 10:42 UTC, benjamreis requested changes
Since we maintain patches we try to limit stylistic changes AMAP

2023-11-17 10:42 UTC, benjamreis commented on XSConsoleData.py
> -
unecessary deletion

2023-11-17 10:42 UTC, benjamreis commented on XSConsoleData.py
> -
same

2023-11-17 10:42 UTC, benjamreis commented on XSConsoleData.py
> -
same

2023-11-17 12:50 UTC, benjamreis approved these changes

2023-11-17 12:50 UTC, merged

2024-06-19 12:09 UTC, benjamreis commented
Upstream contribution included in https://github.com/xapi-project/xsconsole/pull/4